<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LabTestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $lab_tests = [
            'Acetaminophen Level',
            'Acid-Fast Bacillus (AFB) Tests',
            'ADHD Screening',
            'Adrenocorticotropic Hormone (ACTH)',
            'Albumin Blood Test',
            'Alcohol Use Screening Tests',
            'Aldosterone Test',
            'Alkaline Phosphatase',
            'Allergy Blood Test',
            'Allergy Skin Test',
            'Alpha Fetoprotein (AFP) Tumor Marker Test',
            'Alpha-1 Antitrypsin Testing',
            'Alpha-Fetoprotein (AFP) Test',
            'ALT Blood Test',
            'Ammonia Levels',
            'Amniocentesis (amniotic fluid test)',
            'Amylase Test',
            'ANA (Antinuclear Antibody) Test',
            'Anion Gap Blood Test',
            'Anoscopy',
            'Anti-Müllerian Hormone Test',
            'Antibiotic Sensitivity Test',
            'Antibody Serology Tests',
            'Antineutrophil Cytoplasmic Antibodies (ANCA) Test',
            'Appendicitis Tests',
            'Arterial Blood Gas (ABG) Test',
            'AST Test',
            'At-Home Medical Tests',
            'Autism Spectrum Disorder (ASD) Screening',
            'Autonomic Testing',
            'Bacteria Culture Test',
            'Bacterial Vaginosis Test',
            'Balance Tests',
            'Barium Swallow',
            'Basic Metabolic Panel (BMP)',
            'BCR-ABL1 Genetic Test',
            'Beta 2 Microglobulin (B2M) Tumor Marker Test',
            'Bilirubin Blood Test',
            'Bilirubin in Urine',
            'Blood Alcohol Level',
            'Blood Differential',
            'Blood Glucose Test',
            'Blood in Urine',
            'Blood Smear',
            'Bone Density Scan',
            'Bone Marrow Tests',
            'BRAF Genetic Test',
            'BRCA Genetic Test',
            'Breast Biopsy',
            'Bronchoscopy and Bronchoalveolar Lavage (BAL)',
            'BUN (Blood Urea Nitrogen)',
            'Burn Evaluation',
            'C-Peptide Test',
            'C-Reactive Protein (CRP) Test',
            'C. diff Testing',
            'CA 19-9 Blood Test (Pancreatic Cancer)',
            'CA-125 Blood Test (Ovarian Cancer)',
            'Calcitonin Test',
            'Calcium Blood Test',
            'Calcium in Urine Test',
            'Calprotectin Stool Test',
            'Carbon Dioxide (CO2) in Blood',
            'Catecholamine Tests',
            'CCP Antibody Test',
            'CD4 Lymphocyte Count',
            'CEA Test',
            'Celiac Disease Screening',
            'Cerebrospinal Fluid (CSF) Analysis',
            'Ceruloplasmin Test',
            'Chickenpox and Shingles Tests',
            'Chlamydia Test',
            'Chloride Blood Test',
            'Cholesterol Levels',
            'Chorionic Villus Sampling (CVS)',
            'Chymotrypsin in Stool',
            'Coagulation Factor Tests',
            'Cognitive Testing',
            'Cold Stimulation Test',
            'Colorectal Cancer Screening Tests',
            'Colposcopy',
            'Complement Blood Test',
            'Complete Blood Count (CBC)',
            'Comprehensive Metabolic Panel (CMP)',
            'Concussion Tests',
            'Cord Blood Testing and Banking',
            'Cortisol Test',
            'Creatine Kinase',
            'Creatinine Test',
            'Crystals in Urine',
            'CSF Immunoglobulin G (IgG) Index',
            'Cytomegalovirus (CMV) Tests',
            'D-Dimer Test',
            'Dengue Fever Test',
            'Dental Exam',
            'Depression Screening',
            'Developmental and Behavioral Screening Tests',
            'DHEA Sulfate Test',
            'Diabetes Tests',
            'Diabetic Foot Exam',
            'Differential Diagnosis',
            'Doppler Ultrasound',
            'Down Syndrome Tests',
            'Drug Testing',
            'Drug Use Screening Tests',
            'Dysphagia Tests',
            'Elastography',
            'Electrocardiogram',
            'Electrolyte Panel',
            'Electromyography (EMG) and Nerve Conduction Studies',
            'Epithelial Cells in Urine',
            'Erythrocyte Sedimentation Rate (ESR)',
            'Esophageal pH Test',
            'Estrogen Levels Test',
            'Estrogen Receptor, Progesterone Receptor Tests',
            'Fall Risk Assessment',
            'Fasting for a Blood Test',
            'Fecal Occult Blood Test (FOBT)',
            'Ferritin Blood Test',
            'Fetal Alcohol Spectrum Disorders (FASD) Screening',
            'Flu (Influenza) Test',
            'Fluoroscopy',
            'Follicle-Stimulating Hormone (FSH) Levels Test',
            'Food Allergy Testing',
            'Free Light Chains',
            'Fungal Culture Test',
            'G6PD Test',
            'Galactosemia Tests',
            'Gamma-glutamyl Transferase (GGT) Test',
            'Gastric Emptying Tests',
            'Glaucoma Tests',
            'Globulin Test',
            'Glomerular Filtration Rate (GFR) Test',
            'Glucagon Blood Test',
            'Glucose in Urine Test',
            'Gonorrhea Test',
            'Gram Stain',
            'Growth Hormone Tests',
            'Haptoglobin (HP) Test',
            'Hearing Tests for Adults',
            'Hearing Tests for Children',
            'Heart Disease Risk Assessment',
            'Heavy Metal Blood Test',
            'Helicobacter Pylori (H. Pylori) Tests',
            'Hematocrit Test',
            'Hemoglobin A1C (HbA1c) Test',
            'Hemoglobin Electrophoresis',
            'Hemoglobin Test',
            'Hepatitis Panel',
            'HER2 Tumor Marker Test',
            'Herpes (HSV) Test',
            'HIV Screening Test',
            'HIV Viral Load',
            'Homocysteine Test',
            'Human Papillomavirus (HPV) Test',
            'Hysteroscopy',
            'IGF-1 (Insulin-like Growth Factor 1) Test',
            'Immunoglobulins Blood Test',
            'Insulin in Blood',
            'Intravenous Pyelogram (IVP)',
            'Iron Tests',
            'Karyotype Genetic Test',
            'Ketones in Blood',
            'Ketones in Urine',
            'Kidney Stone Analysis',
            'Lactate Dehydrogenase (LDH) Isoenzymes Test',
            'Lactate Dehydrogenase (LDH) Test',
            'Lactate Test',
            'Lactose Tolerance Tests',
            'Laparoscopy',
            'Legionella Tests',
            'Lipase Tests',
            'Lipoprotein (a) Blood Test',
            'Liver Function Tests',
            'Lung Cancer Genetic Tests',
            'Lung Function Tests',
            'Luteinizing Hormone (LH) Levels Test',
            'Lyme Disease Tests',
            'Magnesium Blood Test',
            'Malaria Tests',
            'MCV (Mean Corpuscular Volume)',
            'Measles and Mumps Tests',
            'Measuring Blood Pressure',
            'Meningococcal Disease Tests',
            'Mental Health Screening',
            'Methylmalonic Acid (MMA) Test',
            'Microalbumin Creatinine Ratio',
            'Mononucleosis (Mono) Tests',
            'MPV Blood Test',
            'MRSA Tests',
            'MTHFR Mutation Test',
            'Mucus in Urine',
            'Myasthenia Gravis Tests',
            'Myelography',
            'Nasal Swab',
            'Natriuretic Peptide Tests (BNP, NT-proBNP)',
            'Neurological Exam',
            'Nitrites in Urine',
            'Nonstress Test',
            'Obesity Screening',
            'Obsessive Compulsive Disorder (OCD) Test',
            'Opioid Testing',
            'Osmolality Tests',
            'Ova and Parasite Test',
            'Panic Disorder Test',
            'Pap Smear',
            'Parainfluenza Tests',
            'Parathyroid Hormone (PTH) Test',
            'Partial Thromboplastin Time (PTT) Test',
            'PCR Tests',
            'PDL1 (Immunotherapy) Tests',
            'PET Scan',
            'Pharmacogenetic Tests',
            'Phenylketonuria (PKU) Screening',
            'Phosphate in Blood',
            'Phosphate in Urine',
            'Platelet Tests',
            'Pleural Fluid Analysis',
            'Pneumococcal Disease Tests',
            'Porphyrin Tests',
            'Postpartum Depression Screening',
            'Potassium Blood Test',
            'Prealbumin Blood Test',
            'Pregnancy Test',
            'Prenatal Cell-Free DNA Screening',
            'Prenatal Panel',
            'Procalcitonin Test',
            'Progesterone Test',
            'Prolactin Levels',
            'Prostate-Specific Antigen (PSA) Test',
            'Protein C and Protein S Tests',
            'Protein Electrophoresis by Immunofixation Blood Test',
            'Protein in Urine',
            'Prothrombin Time Test and INR (PT/INR)',
            'PTEN Genetic Test',
            'Pulse Oximetry',
            'Rapid Tests',
            'Rash Evaluation',
            'RDW (Red Cell Distribution Width)',
            'Red Blood Cell (RBC) Count',
            'Red Blood Cell (RBC) Indices',
            'Red Blood Cell Antibody Screen',
            'Renin Test',
            'Respiratory Pathogens Panel',
            'Respiratory Syncytial Virus (RSV) Tests',
            'Reticulocyte Count',
            'Rheumatoid Factor (RF) Test',
            'Salicylates Level',
            'Semen Analysis',
            'Sentinel Lymph Node Biopsy',
            'Sexually Transmitted Infection (STI) Tests',
            'SHBG Blood Test',
            'Skin Biopsy',
            'Skin Cancer Screening',
            'Sleep Study',
            'Smooth Muscle Antibody (SMA) Test',
            'Sodium Blood Test',
            'Sputum Culture',
            'Stool Elastase',
            'Strep A Test',
            'Strep B Test',
            'Stress Tests',
            'Suicide Risk Screening',
            'Sweat Test for Cystic Fibrosis',
            'Synovial Fluid Analysis',
            'Syphilis Tests',
            'Testosterone Levels Test',
            'Therapeutic Drug Monitoring',
            'Thyroglobulin',
            'Thyroid Antibodies',
            'Thyroxine (T4) Test',
            'Total Protein and Albumin/Globulin (A/G) Ratio',
            'TP53 Genetic Test',
            'Trichomoniasis Test',
            'Tricyclic Antidepressant (TCA) Screen',
            'Triglycerides Test',
            'Triiodothyronine (T3) Tests',
            'Troponin Test',
            'TSH (Thyroid-stimulating hormone) Test',
            'Tuberculosis Screening',
            'Tumor Marker Tests',
            'Ultrasound',
            'Uric Acid Test',
            'Urobilinogen in Urine',
            'V/Q Scan',
            'Videonystagmography (VNG)',
            'Vision Screening',
            'Vitamin B Test',
            'Vitamin D Test',
            'Vitamin E (Tocopherol) Test',
            'White Blood Cell (WBC) in Stool',
            'White Blood Count (WBC)',
            'Whooping Cough Tests',
            'Xylose Testing',
            'Yeast Infection Tests',
            'Zika Virus Test',
            '17-Hydroxyprogesterone',
        ];

        foreach ($lab_tests as $test_name) {
            Service::create([
                'name' => $test_name,
                'department' => 'Laboratory',
                'price' => 0, // Default price
            ]);
        }
    }
}
